Import('benchEnv')
stampEnv = benchEnv.Clone()

# Shouldn't benchEnv already contain these ?
Import('mcoreLibrary')
Import('mtmLibrary')
Import('pmallocLibrary')

stampEnv.Append(CCFLAGS = '-Ibench/stamp-kozy/lib -Ibench/stamp-kozy/lib/ptm')
stampEnv.Append(CPPPATH = ['#library/common'])
stampEnv.Append(CCFLAGS = '-fno-omit-frame-pointer')
stampEnv.Append(LIBS = [mcoreLibrary])
stampEnv.Append(LIBS = [mtmLibrary])
stampEnv.Append(LIBS = [pmallocLibrary])
stampEnv.Append(LIBS = ['pthread'])
stampEnv.Append(CCFLAGS = ' -O0')

stamp_list = Split("""
		   vacation
                   """)

sconscript_path = 'vacation/SConscript'

# Build library for persistent variables
pvarLibrary = None
stampEnv['BUILD_PVAR'] = True
Export('stampEnv')
pvarLibrary = SConscript(sconscript_path)
Export('pvarLibrary')

# Build STAMP benchmark
stampEnv['BUILD_PVAR'] = False
Export('stampEnv')
SConscript(sconscript_path)

