Import('benchEnv')
memcachedEnv = benchEnv.Clone() 

# $(CC) $(CCFLAGS) $(CPPPATH)
memcachedEnv.Append(CCFLAGS = ' -O2')
memcachedEnv.Append(CCFLAGS = ' -fno-omit-frame-pointer')
memcachedEnv.Append(CCFLAGS = ' -D_GNU_SOURCE ')
memcachedEnv.Append(CCFLAGS = ' -DHAVE_CONFIG_H ')

memcachedEnv.Append(CPPPATH = ['#bench/memcached/memcached-1.2.4-mtm'])

sconscript_path = 'memcached-1.2.4-mtm/SConscript'

# Build library for persistent variables
pvarLibrary = None
memcachedEnv['BUILD_PVAR'] = True
Export('memcachedEnv')
pvarLibrary = SConscript(sconscript_path)
Export('pvarLibrary')

# Build Memcached using the library for 
# handling persistent variables
memcachedEnv['BUILD_PVAR'] = False
Export('memcachedEnv')
SConscript(sconscript_path)
