Import('benchEnv')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('pmallocLibrary')

stlEnv = benchEnv.Clone() 
stlEnv.Append(CCFLAGS = ' -D_GNU_SOURCE ')
stlEnv.Append(CPPPATH = ['#library/common'])
stlEnv.Append(CCFLAGS = '-fno-omit-frame-pointer')
stlEnv.Append(CCFLAGS = '-O2')


boostEnv = stlEnv.Clone() 
boostEnv.Append(LIBS = ['boost_program_options', 'boost_serialization', 'boost_filesystem'])
boostEnv.Program('with_boost', 'with_boost.cxx')


# IMPORTANT: The order we link libraries matters: 
# boost_program_options MUST be before mcoreLibrary
#
# Otherwise we get a segfault!
#
# Also, Tack used this option -cxxlib-nostd (see Makefile-deprecated)

mnemosyneEnv = stlEnv.Clone() 
mnemosyneEnv.Append(LIBS = ['boost_program_options'])
mnemosyneEnv.Append(LIBS = [mcoreLibrary])
mnemosyneEnv.Append(LIBS = [mtmLibrary])
mnemosyneEnv.Append(LIBS = [pmallocLibrary])
mnemosyneEnv.Append(CPPPATH = ['stl', 'stl/x86_64-redhat-linux6E'])
mnemosyneEnv.Program('with_mnemosyne', ['with_mnemosyne.cxx', 'tree.cc'])
