Import('ubenchEnv')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('pmallocLibrary')

myEnv = ubenchEnv.Clone() 
myEnv.Append(CPPPATH = ['#library/common'])

sources = Split("""
                main.c
                """)


myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Append(LIBS = [pmallocLibrary])
myEnv.Program('instrument_cost', sources)
