Import('kvstoreEnv')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('pmallocLibrary')

myEnv = kvstoreEnv.Clone() 
myEnv.Append(CCFLAGS = ' -D_GNU_SOURCE ')
myEnv.Append(CPPPATH = ['#library/common'])

sources = Split("""
		hashtable.c
                """)

hashtableLibrary = myEnv.StaticLibrary('ht', sources)

Return('hashtableLibrary')
