Import('kvstoreEnv')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('mallocLibrary')
Import('hashtableLibrary')

myEnv = kvstoreEnv.Clone() 
myEnv.Append(CCFLAGS = ' -D_GNU_SOURCE ')
myEnv.Append(CPPPATH = ['#library'])
myEnv.Append(CPPPATH = ['#library/common'])
myEnv.Append(CPPPATH = ['#bench/kvstore/tc/library-mtm'])
myEnv.Append(CPPPATH = ['#bench/kvstore/ht'])

myEnv['EXPLICIT_DEPENDENCY']['TC_MTM_LIB'] = '/home/hvolos/workspace.prometheus/mnemosyne/src/usermode/bench/kvstore/tc/library-mtm/libtokyocabinet.a'

#myEnv.Append(CPPPATH = myEnv['EXPLICIT_DEPENDENCY']['TC_MTM_INCLUDE'] )
myEnv.Append(LINKFLAGS = '-Wl,--whole-archive %s -Wl,--no-whole-archive' % myEnv['EXPLICIT_DEPENDENCY']['TC_MTM_LIB'])

myEnv.Append(LINKFLAGS = '-lbz2 -lz')
sources = Split("""
		experiment/mnemosyne.c
                """)


myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Append(LIBS = [mallocLibrary])
myEnv.Program('mytest', sources)
