Import('stampEnv')

stampEnv.Append(CCFLAGS = '-DMAP_USE_RBTREE -DLIST_NO_DUPLICATES')
sources = Split("""     client.c
			customer.c
			manager.c
			reservation.c
			vacation.c
			../lib/list.c
			../lib/pair.c
			../lib/mt19937ar.c
			../lib/random.c
			../lib/rbtree.c
			../lib/thread.c
		""")

stampEnv.Program('vacation', sources)
