import os

Import('pmallocLibrary')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('benchEnv')

ubenchEnv = benchEnv.Clone() 

if ubenchEnv['BUILD_DEBUG'] == True:
	ubenchEnv.Append(CCFLAGS = ' -g')
else:	
	ubenchEnv.Append(CCFLAGS = ' -O2')

Export('ubenchEnv')

ubench_list = Split("""
                instrument_cost
                sync
                tmlog
		rawlog
                """)

for ubench in ubench_list:
	sconscript_path = ubench + '/SConscript'
	SConscript(sconscript_path)
