from configuration import TinyStm
env = TinyStm.Environment('default')

stm_library_sources = [
	'src/stm.c'
]

module_sources = [
	'src/mod_local.c',
	'src/mod_mem.c',
	'src/mod_print.c',
	'src/mod_stats.c'
]

wrapper_sources = [
	'src/wrappers.c'
]

env.Library('libstm',
        [stm_library_sources, module_sources, wrapper_sources])
