import os
from library.configuration import mnemosyne

AddOption('--example',
           action="store", dest='selected_example',
           type='string',
           metavar='NAME',
           help='build this example')
AddOption("--build-debug",
           action="store_true", dest="build_debug", 
           default = True,
           help="build library with debug info [default]")
AddOption("--linkage",
           action="store", dest="linkage", 
           type="choice", choices=["dynamic", "static"],
           default = "dynamic",
           help="library linkage: dynamic, static [default: %default]")


env = mnemosyne.Environment()
env['BUILD_DEBUG'] = GetOption('build_debug')
env['LINKAGE'] = GetOption('linkage')
env['EXAMPLE'] = GetOption('selected_example')
rootDir = os.getcwd()
env['MY_ROOT_DIR'] = rootDir
env['MY_UTIL_DIR'] = os.path.join(rootDir, 'util')
Export('env')

MnemosyneLibrary, MtmLibrary = SConscript('library/SConscript', variant_dir = 'build/library')

if env['EXAMPLE'] != None:
	Export('MnemosyneLibrary', 'MtmLibrary')
	SConscript('examples/SConscript')
