Import('kvstoreEnv')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('mallocLibrary')
Import('hashtableLibrary')

myEnv = kvstoreEnv.Clone() 
myEnv.Append(CCFLAGS = ' -D_GNU_SOURCE ')
myEnv.Append(CPPPATH = ['#library/common'])
myEnv.Append(CPPPATH = ['#bench/kvstore/ht'])
myEnv.Append(CPPPATH = ['/home/hvolos/workspace/db-4.8.26/build_unix'])

bdbLibrary = '/scratch/workspace/db-4.8.26/build_unix/libdb.a'
myEnv.Append(LINKFLAGS = '-Wl,--whole-archive /home/hvolos/workspace/db-4.8.26/build_unix/libdb.a -Wl,--no-whole-archive')

sources = Split("""
		bdb_mix.c
                main.c
		mtm_mix.c
                """)


myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Append(LIBS = [mallocLibrary])
myEnv.Append(LIBS = [hashtableLibrary])

myEnv.Program('kvdriver', sources)
