Import('kvstoreEnv')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('mallocLibrary')
Import('hashtableLibrary')

myEnv = kvstoreEnv.Clone() 
myEnv.Append(CCFLAGS = ' -D_GNU_SOURCE ')
myEnv.Append(CPPPATH = ['#library/common'])
myEnv.Append(CPPPATH = ['#bench/kvstore/ht'])
myEnv.Append(CPPPATH = ['#bench/kvstore/kvdriver/common'])

myEnv.Append(CPPPATH = myEnv['EXPLICIT_DEPENDENCY']['BDB_INCLUDE'] )
myEnv.Append(LINKFLAGS = '-Wl,--whole-archive %s -Wl,--no-whole-archive' % myEnv['EXPLICIT_DEPENDENCY']['BDB_LIB'])

myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Append(LIBS = [mallocLibrary])


# Hashtable & BDB kvdriver

htEnv = myEnv.Clone() 
sources_ht = Split("""
                   common/main.c
		   ht/bdb_mix.c
		   ht/mtm_mix.c
		   ht/ubench.c
                   """)


htEnv.Append(CPPPATH = ['#bench/kvstore/kvdriver/ht'])
htEnv.Append(LIBS = [hashtableLibrary])
htEnv.Program('kvdriver-ht', sources_ht)



# TokyoCabinet kvdriver
#
# We build a separate kvdriver for the two flavors of TokyoCabinet as 
# we cannot link kvdriver to both TokyoCabinet libraries.

sources_tc_base = Split("""
		        bdb_mix.c
                        main.c
		        mtm_mix.c
                        """)
			
sources_tc_mtm = Split("""
	                bdb_mix.c
                        main.c
		        mtm_mix.c
                        """)


#myEnv.Program('kvdriver-tc-base', sources_tc_base)
#myEnv.Program('kvdriver-tc-mtm', sources_tc_mtm)
