Import('ubenchEnv')
Import('mcoreLibrary')
Import('mtmLibrary')

myEnv = ubenchEnv.Clone() 
myEnv.Append(CPPPATH = ['#library/common'])


myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Program('tmlog', 'throughput.c')
myEnv.Program('tmlog_latency', 'latency.c')
