rm ./clients/tools/Makefile
rm ./clients/Makefile
rm ./include/Makefile
rm ./libraries/liblunicode/Makefile
rm ./libraries/liblber/Makefile
rm ./libraries/liblutil/Makefile
rm ./libraries/Makefile
rm ./libraries/libldap/Makefile
rm ./libraries/libldap_r/Makefile
rm ./libraries/librewrite/Makefile
rm ./doc/man/man1/Makefile
rm ./doc/man/man5/Makefile
rm ./doc/man/man8/Makefile
rm ./doc/man/Makefile
rm ./doc/man/man3/Makefile
rm ./doc/Makefile
rm ./tests/progs/Makefile
rm ./tests/Makefile
rm ./Makefile
rm ./servers/slurpd/Makefile
rm ./servers/slapd/slapi/Makefile
rm ./servers/slapd/back-ldap/Makefile
rm ./servers/slapd/back-meta/Makefile
rm ./servers/slapd/back-dnssrv/Makefile
rm ./servers/slapd/back-mnemosyne/Makefile
rm ./servers/slapd/back-ldbm/Makefile
rm ./servers/slapd/back-sql/Makefile
rm ./servers/slapd/back-ldif/Makefile
rm ./servers/slapd/back-passwd/Makefile
rm ./servers/slapd/overlays/Makefile
rm ./servers/slapd/back-perl/Makefile
rm ./servers/slapd/back-null/Makefile
rm ./servers/slapd/back-hdb/Makefile
rm ./servers/slapd/back-bdb/Makefile
rm ./servers/slapd/Makefile
rm ./servers/slapd/back-monitor/Makefile
rm ./servers/slapd/back-relay/Makefile
rm ./servers/slapd/shell-backends/Makefile
rm ./servers/slapd/back-shell/Makefile
rm ./servers/Makefile
