Import('ubenchEnv')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('mallocLibrary')

myEnv = ubenchEnv.Clone() 
myEnv.Append(CCFLAGS = ' -D_GNU_SOURCE ')
myEnv.Append(CPPPATH = ['#library/common'])
myEnv.Append(CPPPATH = ['/home/hvolos/workspace/db-4.8.26/build_unix'])

bdbLibrary = '/scratch/workspace/db-4.8.26/build_unix/libdb.a'
myEnv.Append(LINKFLAGS = '-Wl,--whole-archive /home/hvolos/workspace/db-4.8.26/build_unix/libdb.a -Wl,--no-whole-archive')

sources = Split("""
		bdb_mix.c
		hashtable.c
                main.c
		mtm_mix.c
		txmutex.c
                """)


myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Append(LIBS = [mallocLibrary])
myEnv.Program('hashtable', sources)
