Import('examplesEnv')
Import('mcoreLibrary')
Import('mtmLibrary')

myEnv = examplesEnv.Clone() 
myEnv.Append(CPPPATH = ['#library/common'])

sources = Split("""
                main.cxx
                ../../library/mtm/src/mode/pwb/tmlog_tornbit.c
                """)


myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Program('log', sources)
