import os

Import('examplesEnv')

examplesEnv['CPPPATH'] = ['#library/mnemosyne/include', '#library/mtm/include']

if examplesEnv['BUILD_DEBUG'] == True:
	examplesEnv.Append(CCFLAGS = ' -g')
else:	
	examplesEnv.Append(CCFLAGS = ' -O2')

examplesEnv.Append(CCFLAGS = ' -m64 ')
examplesEnv.Append(LINKFLAGS = ' -T '+ examplesEnv['MY_UTIL_DIR'] + '/linker_script_persistent_segment_m64')
Export('examplesEnv')

example = examplesEnv['EXAMPLE']
sconscript_path = example + '/SConscript'
SConscript(sconscript_path)
