import os

Import('examplesEnv')
Import('MallocLibrary')

examplesEnv['CC'] = '/opt/intel/Compiler/11.0/606/bin/intel64/icc'
examplesEnv['CXX'] = '/opt/intel/Compiler/11.0/606/bin/intel64/icpc'

examplesEnv['CPPPATH'] = ['#library/mnemosyne/include', '#library/mtm/include']
examplesEnv.Append(CCFLAGS = ' -Qtm_enabled ')
examplesEnv.Append(LINKFLAGS = ' -Qtm_enabled ')
examplesEnv.Append(LIBS = [MallocLibrary])

if examplesEnv['BUILD_DEBUG'] == True:
	examplesEnv.Append(CCFLAGS = ' -g')
else:	
	examplesEnv.Append(CCFLAGS = ' -O2')

examplesEnv.Append(CCFLAGS = ' -m64 ')
examplesEnv.Append(LINKFLAGS = ' -T '+ examplesEnv['MY_UTIL_DIR'] + '/linker_script_persistent_segment_m64')
Export('examplesEnv')

example = examplesEnv['EXAMPLE']
sconscript_path = example + '/SConscript'
SConscript(sconscript_path)
