import sys
from configuration import test
testEnv = test.Environment('default')

# For correct and complete compilation.
testEnv.Append(CCFLAGS = ' -m64 -g')
testEnv.Append(LINKFLAGS = ' -T '+ 'util/linker_script_persistent_segment_m64')

# LibMTM Unit Tests
Import('MtmLibrary', 'MnemosyneLibrary')
testEnv.Append(CPPPATH = ['#library/mtm/src/sysdeps/linux', '#library/mtm/src'])
mtm_tests = testEnv.Program('mtm_tests', source = [Glob('mtm/*.tests.cxx'), Glob('mtm/*.fixtures.cxx'), 'main.cxx'], LIBS=['UnitTest++', MnemosyneLibrary, MtmLibrary])
Return('mtm_tests')
