Import('examplesEnv')
Import('MnemosyneLibrary')
Import('MtmLibrary')

myEnv = examplesEnv.Clone()

sources = Split("""
                main.cxx
                """)

myEnv.Append(LIBS = [MnemosyneLibrary])
myEnv.Append(LIBS = [MtmLibrary])
myEnv.Program('simple', sources)
