Import('examplesEnv')
Import('MnemosyneLibrary')
Import('MtmLibrary')

myEnv = examplesEnv.Clone()

sources = Split("""
                main.cxx
                """)

myEnv.Program('simple', sources, LIBS=[MnemosyneLibrary, MtmLibrary])
