Import('benchEnv')
Import('mcoreLibrary')
Import('mtmLibrary')
Import('mallocLibrary')

kvstoreEnv = benchEnv.Clone() 
kvstoreEnv.Append(CCFLAGS = ' -D_GNU_SOURCE ')
kvstoreEnv.Append(CPPPATH = ['#library/common'])
Export('kvstoreEnv')

hashtableLibrary = SConscript('ht/SConscript')
Export('hashtableLibrary')

SConscript('kvdriver/SConscript')
